drop table cd if exists;
create table cd (title varchar(128),artist varchar(128),country varchar(128),company varchar(128),price float,year int);
insert into cd (title,artist,country,company,price,year) values ('Empire Burlesque','Bob Dylan','USA','''asd''''''''','10.90','1985');
insert into cd (title,artist,country,company,price,year) values ('Hide your heart','Bonnie Tyler','UK','CBS Records','9.90','1988');
insert into cd (title,artist,country,company,price,year) values ('Greatest Hits','Dolly Parton','USA','RCA','9.90','1982');
insert into cd (title,artist,country,company,price,year) values ('Still got the blues','Gary Moore','UK','Virgin records','10.20','1990');
insert into cd (title,artist,country,company,price,year) values ('Eros','Eros Ramazzotti','EU','BMG','9.90','1997');
insert into cd (title,artist,country,company,price,year) values ('One night only','Bee Gees','UK','Polydor','10.90','1998');
insert into cd (title,artist,country,company,price,year) values ('Sylvias Mother','Dr.Hook','UK','CBS','8.10','1973');
insert into cd (title,artist,country,company,price,year) values ('Maggie May','Rod Stewart','UK','Pickwick','8.50','1990');
insert into cd (title,artist,country,company,price,year) values ('Romanza','Andrea Bocelli','EU','Polydor','10.80','1996');
insert into cd (title,artist,country,company,price,year) values ('When a man loves a woman','Percy Sledge','USA','Atlantic','8.70','1987');
insert into cd (title,artist,country,company,price,year) values ('Black angel','Savage Rose','EU','Mega','10.90','1995');
insert into cd (title,artist,country,company,price,year) values ('1999 Grammy Nominees','Many','USA','Grammy','10.20','1999');
insert into cd (title,artist,country,company,price,year) values ('For the good times','Kenny Rogers','UK','Mucik Master','8.70','1995');
insert into cd (title,artist,country,company,price,year) values ('Big Willie style','Will Smith','USA','Columbia','9.90','1997');
insert into cd (title,artist,country,company,price,year) values ('Tupelo Honey','Van Morrison','UK','Polydor','8.20','1971');
insert into cd (title,artist,country,company,price,year) values ('Soulsville','Jorn Hoel','Norway','WEA','7.90','1996');
insert into cd (title,artist,country,company,price,year) values ('The very best of','Cat Stevens','UK','Island','8.90','1990');
insert into cd (title,artist,country,company,price,year) values ('Stop','Sam Brown','UK','A and M','8.90','1988');
insert into cd (title,artist,country,company,price,year) values ('Bridge of Spies','T Pau','UK','Siren','7.90','1987');
insert into cd (title,artist,country,company,price,year) values ('Private Dancer','Tina Turner','UK','Capitol','8.90','1983');
insert into cd (title,artist,country,company,price,year) values ('Midt om natten','Kim Larsen','EU','Medley','7.80','1983');
insert into cd (title,artist,country,company,price,year) values ('Pavarotti Gala Concert','Luciano Pavarotti','UK','DECCA','9.90','1991');
insert into cd (title,artist,country,company,price,year) values ('The dock of the bay','Otis Redding','USA','Atlantic','7.90','1987');
insert into cd (title,artist,country,company,price,year) values ('Picture book','Simply Red','EU','Elektra','7.20','1985');
insert into cd (title,artist,country,company,price,year) values ('Red','The Communards','UK','London','7.80','1987');
insert into cd (title,artist,country,company,price,year) values ('Unchain my heart','Joe Cocker','USA','EMI','8.20','1987');
